version: '2'
services:
  bot:
    image: futebot/futebot:latest
    env_file: keys.env
    volumes:
      - .:/usr/src/app
  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
